Add tests that specifically check rendering.
snarfed/wordpress-micropub pull request #142
Opened 2018-07-22 14:58 UTC by dshanske

I have additional plans to break the testing apart in this manner, but wanted to submit this for feedback before I went further. 

The tests for rendering microformats test the entire process from start to finish. But as displaying microformats was broken out subsequent to their writing to be triggered by the micropub_post_content filter, it makes more sense in my opinion to just test this filter by itself.

As a positive note, this would mean, if you wanted to add things dynamically, you could hook the same function into the content filter and add microformats on the fly, or other configurations....which is why I want to test this way.

My intention is to work similarly for the geodata tests. 

This moves me closer to the previously stated goals.

2018-07-23 14:16 UTC, snarfed reviewed
this absolutely makes sense. thank you for doing it.

i assume you also plan to delete the existing tests that these were copied from?

2018-07-23 14:16 UTC, snarfed commented on tests/test_render.php
> +	function check_create_content_html() {
remove?

2018-07-23 14:16 UTC, snarfed commented on tests/test_render.php
> +	function _test_create_interaction_json( $property ) {
minor nit: probably just `create_interaction_json`

2018-07-23 14:16 UTC, snarfed commented on tests/test_render.php
> +	public static function setUpBeforeClass() {
i expect you can delete this

2018-07-23 14:16 UTC, snarfed commented on tests/test_render.php
> +	public function setUp() {
this too

2018-07-24 02:46 UTC, dshanske commented
@snarfed Going to continue in this vein, but this one has been updated as requested if you want to approve.

2018-07-24 19:19 UTC, snarfed requested changes
in general, this looks good. thanks!

one key point is that the new tests only cover the code paths _after_ deserializing the input form-encoded or json data. the old tests also tested those paths. so we should probably keep a few of the old ones around, notably one each of the `_post` (form-encoded) and `_json` tests, to keep testing those code paths.

2018-07-24 19:19 UTC, snarfed commented on tests/test_render.php
> +	function create_interaction_json( $property ) {
minor nit: remove `_json`, since this is after decoding the input data, ie not json specific.

2018-07-24 19:19 UTC, snarfed commented on tests/test_render.php
> +	function test_create_event_json() {
ditto

2018-07-25 00:09 UTC, dshanske commented
With the paths, I was going to do one straight through in the next PR. Already in progress

2018-07-25 00:34 UTC, snarfed commented
great! you'll need at least two, for json vs form encoded.

generally i prefer to keep PRs atomic and not have any PR regress in functionality or test coverage. especially since in this case it's as easy as most not deleting a couple of the existing tests, especially since they do test these code paths fine as is, you don't really need to write new test(s). but if the next PR will include the replacement tests, sounds good.

2018-07-25 00:34 UTC, snarfed approved these changes

2018-07-25 04:16 UTC, merged